### PR TITLE
Fixing typo on spanish translation

### PR DESCRIPTION
**Pull request by julienmartin**

### CODE REVIEW

**Comment by sdras** [comment]
thanks!

**Comment by sdras** [comment]
Oh, wait, there are some conflicts that need to be addressed on this first before I can merge

**Comment by Gonzalo2310** [comment]
Thank you for the improvements @julienmartin

**Comment by julienmartin** [comment]
@sdras No more conflicts!
@Gonzalo2310 You're welcome!

**Comment by sdras** [comment]
Thank you @julienmartin!

**Pull request merged**
