### PR TITLE
Translated into Chinese

### PR DESCRIPTION
**Pull request by proYang**

### CODE REVIEW

**Comment by welll** [comment]
@proYang I believe that will be easier add the translation after this PR (https://github.com/sdras/array-explorer/pull/22) be merged

**Comment by proYang** [comment]
@welll Thanks, I will continue to pay attention. 🎉

**Comment by sdras** [comment]
Thank you so much!!! You are awesome. I'm going to merge this in, would you mind making the other updates in another PR that change up the text in the components as well? 🎉

**Comment by proYang** [comment]
Ha ha ha, of course no problem. I will continue to pay attention to the Chinese version of this project. :rose:

**Pull request merged**
