### PR TITLE
spanish docs

### PR DESCRIPTION
**Pull request by Gonzalo2310**
This doesn't finish the job.
The components have English text inside.
Texts should be outsourced.
It's a breakthrough anyway.

### CODE REVIEW

**Comment by sdras** [comment]
This is amazing! I love it. Thank you so much. I'll work on making a language switcher and incorporating it.

**Comment by Gonzalo2310** [comment]
It is necessary to solve even the text within the components vue

**Comment by sdras** [comment]
yeah, let me look at some other projects that have language switchers and how they set up their components

**Comment by Gonzalo2310** [comment]
Of course. As long as you need. And you had a really good idea.

**Pull request merged**
