### PR TITLE
Update Chinese translation

### PR DESCRIPTION
**Pull request by g-plane**
According to changes: https://github.com/sdras/array-explorer/commit/5ed6951c74a64ea77174d08e4023fe2e33cb1422 and https://github.com/sdras/array-explorer/commit/3f7cf39265c70f52665e06853580092c27a3cfe5

BTW, maybe we can ask other translators to update other languages?
@salahaa1 @imbyurhan @xgebi @bahe007 @AWolf81 @Gonzalo2310 @julienmartin @galuhsahid @glenngijsberts @welll @TheElderMindseeker @bdimitrovski

### CODE REVIEW

**Comment by bdimitrovski** [comment]
@g-plane Done - in PR https://github.com/sdras/array-explorer/pull/55

**Comment by galuhsahid** [comment]
Done in PR #56, thanks for letting us know!

**Comment by Gonzalo2310** [comment]
Thank you for the warning.

**Comment by sdras** [comment]
Thanks everyone!

**Pull request merged**
